context:
  version: "0.2.0"
package:
  name: kuva
  version: ${{ version }}
source:
  url: https://github.com/Psy-Fer/kuva/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f7f98e6334cbe570e6be960b2d01c0e87ec11315b9fe80ae3c012e13b3600244
build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then: |
          cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
          cargo auditable install --path . --bin kuva --features cli,full --locked --no-track --root ${PREFIX}
        else: |
          cargo-bundle-licenses --format yaml --output %SRC_DIR%\THIRDPARTY.yml
          cargo auditable install --path . --bin kuva --features cli,full --locked --no-track --root %LIBRARY_PREFIX%
requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - if: linux
      then: ${{ compiler('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
tests:
  - script:
      - kuva --help
about:
  homepage: https://psy-fer.github.io/kuva/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: Command-line front-end for the kuva plotting library. It reads tabular data from a TSV or CSV file (or stdin) and writes an SVG, PNG, PDF, to-a-file, or stdout
  summary: Command-line front-end for the kuva plotting library
extra:
  recipe-maintainers:
    - VasanthakumarV
